[alias]
b = "build --release -Z build-std=core,alloc"
c = "clean"

[build]
# Comment the following line to use the system rustc binary
rustc = "psx_rustc"

# The asm output appears in target/mipsel-sony-psx/release/deps/load_delay_test*.s
rustflags = [ "-C", "linker=../mips_toolchain/ld", "--emit=asm"]

# Swap the comment on these lines to switch between the built-in and JSON targets
target = "mipsel-sony-psx"
#target = "./mipsel-sony-psx.json"
