[package]
name = "cargo-psx"
version = "0.1.0"
authors = ["Ayrton <a.munoz3327@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf2psexe = { path = "elf2psexe" }
#toml = "0.5.7"
