[package]
name = "psx"
version = "0.1.0"
authors = ["Ayrton <a.munoz3327@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
# Print heap-less panic messages
pretty_panic = []
# Don't use inlining hints
no_inline_hints = []
# Forbid using undefined behavior to improve performance
forbid_UB = []
# Used to compile tests crate (cannot be used with forbid_UB)
no_std_test = []
