[alias]
b = "build --release"

[build]
rustflags = ["-C", "linker=../mips_toolchain/ld", "-C", "link-args=--script=../mipsel-sony-psx.ld", "-O", "-C", "soft-float"]
target = "../mipsel-sony-psx.json"
