[package]
name = "framebuffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psx = { path = "../../psx" }
libm = "0.2.1"
const-random = "0.1.13"
